%%{init: { "flowchart": { "curve": "linear" }, "logLevel": 2 } }%%
graph LR 
  Stream[sds:Stream]
  E[p-plan:Entity]
  SH[sh:ShapeNode]

  Dataset
  Activity
  RecordType

  A--> |prov:used| E

  subgraph Activity
    A[p-plan:Activity]
    S[p-plan:Step]
    RML[RML]
    Buc[Bucketizer]
    LD[LDESClient]

    Buc.-> S
    LD.-> S
    RML.-> S
    A--> |p-plan:correspondsToStep| S
  end

  Stream--> |sds:shape| SH


  subgraph RecordType
    R[sds:Record]
    Mem[sds:Member]
    IM[sds:ImmutableMember]

    IM.->Mem
    Mem.->R
  end

  Stream--> |sds:carries| R

  subgraph Dataset
    direction LR
    Data[dcat:Dataset]
    TC[tree:Collection]
    SH2[Shape]
    LDS[ldes:EventStream]

    TC-->|tree:shape|SH2
    TC.->Data
    LDS.->TC
  end
  
  Stream .-> E
  Stream--> |p-plan:wasGeneratedBy| A
  Stream --> |sds:dataset|Data 

